# Generated by Django 5.0.1 on 2024-02-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.PositiveBigIntegerField(max_length=14)),
                ('address', models.CharField(max_length=200)),
                ('about', models.TextField(max_length=200)),
                ('education', models.TextField(max_length=100)),
                ('experience', models.TextField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('interests', models.TextField(max_length=100)),
                ('achievements', models.TextField(max_length=100)),
                ('references', models.TextField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
