# Generated by Django 5.0.1 on 2024-02-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='phone',
            field=models.PositiveIntegerField(max_length=14),
        ),
    ]
